## Default values for Lightlytics agent
## See Lightlytics helm documentation:


nameOverride:  # ""

fullnameOverride:  # ""

registry: public.ecr.aws/f1v0s3d7

lightlytics:
  #lightlytics.apiToken --  Lightlytics API token for your Kubernetes cluster
  #ref :
  apiToken: <LightlyticsAPIToken>

  #lightlytics.apiUrl -- Lightlytics site url
  apiUrl: https://app.lightlytics.com

  #lightlytics.fullScanScheduleSeconds -- periodic Kubernetes resources scan at seconds
  fullScanScheduleSeconds: 1800

  #lightlytics.filterRunningPods -- takes only pods which at status running
  filterRunningPods: true

  #lightlytic.fieldSelectorsNamespaces -- filter/unfilter resources from specific namespace
  fieldSelectorsNamespaces:
  
  #lightlytics.workflow -- lightlytics workflow type 
  workflow: full_scan
  
  #lightlytics.port -- lightlytics port
  port: 443

  replicas: 1

  image:
    #lightlytics.image.name -- Lightlytics agent image name.
    name: mika

    #lightlytics.image.tag -- Lightlytics agent tag to use.
    tag: master.266

    #lightlytics.image.pullPolicy -- Lightlytics agent image pullPolicy
    pullPolicy: IfNotPresent

  serviceAccount:
    #lightlytics.serviceAccount.create
    create: true

    #lightlytics.serviceAccount.name -- The name of the Service account.
    #If not set and create is true, a name is generated using the fullname template
    name:

  resources:
    requests:
      cpu: 50m
      memory: 32Mi
    limits:
     cpu: 400m
     memory: 2048Mi
  env:
    LOGLEVEL: INFO
    DEBUG: False


