{{- if .Values.lightlytics.process_discovery_containers.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "lightlytics.fullname" . }}-process-discovery
  labels:
  {{- include "lightlytics.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
  {{- include "lightlytics.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
    {{- include "lightlytics.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "lightlytics.serviceAccountName" . }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000  
      tolerations:
          {{- toYaml .Values.lightlytics.tolerations | nindent 8 }}
      containers:
      {{- range $container_name, $container_values := .Values.lightlytics.process_discovery_containers.containers }}
        - name: {{ $container_name }}
          image: {{ template "lightlytics.process-discovery-image-path" $}}
          imagePullPolicy: {{ $.Values.lightlytics.process_discovery_image.pullPolicy }}
          command:
            {{- range $container_values.command }}
            - {{ . }}
            {{- end }}
          resources:
{{ toYaml $.Values.lightlytics.resources | indent 12 }}
          securityContext:
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities:
                 drop:
                    - all
                 add:
                    - SYS_PTRACE
                    - DAC_READ_SEARCH
          readinessProbe:
              exec:
                 command:
                   - cat
                   - /main.py
              initialDelaySeconds: 30
              periodSeconds: 30
          livenessProbe:
              exec:
                 command:
                   - cat
                   - /main.py
              initialDelaySeconds: 30
              periodSeconds: 30
          env:
            - name: LIGHTLYTICS_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "lightlytics.fullname" $}}
                  key: api-key
            - name: LIGHTLYTICS_API_URL
              value: {{ $.Values.lightlytics.apiUrl | quote }}
            - name: PORT
              value: {{ $.Values.lightlytics.port | quote }}
              
            {{- range $envVarName, $envVarValue := $.Values.lightlytics.env }}
            - name: {{ $envVarName }}
              value: {{ $envVarValue | quote }}
            {{- end }}
          volumeMounts:
            - name: cgroups
              mountPath: /host/sys/fs/cgroup
              readOnly: true
            - name: passwd
              mountPath: /etc/passwd
              readOnly: true
            - name: procdir
              mountPath: /host/proc
              readOnly: true
      volumes:
        - name: cgroups
          hostPath:
            path: /sys/fs/cgroup
        - name: passwd
          hostPath:
            path: /etc/passwd
        - name: procdir
          hostPath:
            path: /proc
    {{- end }}
{{- end }}